### ISSUE TITLE
Feature request: Optional username in /time

### ISSUE THREAD

**Issue by FinOCE** [royalgraphx/Hexley#1]
Rather than requiring the username argument in the `/time` command, it would be nice to be able to optionally not include one, and have it display your current time. Would be easy to implement, as it would just involve making the argument optional and then doing a null check and if so using the interaction user.

**Comment by royalgraphx** [comment]
Thanks for submitting a feature request! Solving for edge cases such as these are of top priority. Your credits have been attributed to the following commit:

https://github.com/royalgraphx/Hexley/commit/af11c3335951fa06fbcf56d549d9823a84bf45a1
